--- # Amazon Web Services Deployment Configurations
cloudProvider/:
  aws:
    defaults: 
      activeCname: ${current.application.name}-${current.environment.name}-active

    # AWS Elasticbeanstalk EB Tool Configurations
    platform/:
      awsElasticbeanstalkEb: 
        defaults: 
          inherit|: ${current.cloudProvider.defaults}
          create: 
            configFile$: ${args.launchFile}
            launch$: single-private-server
          disableLines: [.env]
          ebignoreContent: 
            - '*'
            - '!${args.buildPath}/**'
            - '!${args.packageFile}'
            - '!server.js'


        environment/:
          # STAGING ENVIRONMENT CONFIGURATIONS
          staging: 
            defaults: 
              inherit|: ${current.platform.defaults}
              tokenFile: ${args.secretsPath}/.staging_tokens.yaml
              prompt: password
              create: 
                launch$: single-private-server
            
            group:
              all: [myApi1, myApi2]
            
            application/: 
              myApi1: 
                defaults: 
                  inherit|: ${current.environment.defaults}
                  environmentFile: ${args.envPath}/.env.my_api1.staging
                  env: 
                    readEnv|: ${environmentFile}
                
                # App Configurations
                configuration/: 
                  onOut|: ${checkVariables}
                  
                  # Default Configuration
                  default:
                    inherit|: ${current.application.defaults}
                    create:
                      readYaml|: ${configFile$},${launch$}
                      # readYml function reads yml file as first argument and 
                      # returns value of key that is passed as second argument
                      envvars:
                        - API_PATH=${env.API_PATH}
                        - API_ENDPOINT=${env.API_ENDPOINT}

                        
                  # High Security Configuration
                  highSecurity:
                    inherit|: ${current.application.defaults}
                    create:
                      vpc:
                        securitygroups: [sg-#hash2]

              myApi2: 
                defaults: 
                  inherit|: ${current.environment.defaults}
                  environmentFile: ${args.envPath}/.env.my_api2.staging
                
                # App Configurations
                configuration/: 
                  onOut|: ${checkVariables}
                  
                  # Default Configuration
                  default:
                    inherit|: ${current.application.defaults}
                    launch$: vpc-private-server
                    create:
                      readYaml|: ${configFile$},${launch$}

                  # High Security Configuration
                  highSecurity:
                    inherit|: ${current.application.defaults}
                    create:
                      vpc:
                        securitygroups: [sg-#hash2]

          # PRODUCTION ENVIRONMENT CONFIGURATIONS
          production: 
            defaults: 
              inherit|: ${current.platform.defaults}
              tokenFile: ${args.secretsPath}/.production_tokens.yaml
              prompt: password
              create: 
                launch$: vpc-private-cluster
              buildRun: true
              buildDeploy: true
              
            group:
              all: [myApi1, myApi2]
            
            application/: 
              myApi1: 
                defaults: 
                  inherit|: ${current.environment.defaults}
                  environmentFile: ${args.envPath}/.env.my_api1.production
                
                # App Configurations
                configuration/: 
                  onOut|: ${checkVariables}
                  
                  # Default Configuration
                  default:
                    inherit|: ${current.application.defaults}
                    create:
                      readYaml|: ${configFile$},${launch$}
                      # readYml function reads yml file as first argument and 
                      # returns value of key that is passed as second argument


                  # High Security Configuration
                  highSecurity:
                    inherit|: ${current.application.defaults}
                    create:
                      vpc:
                        securitygroups: [sg-#hash2]

              myApi2: 
                defaults: 
                  inherit|: ${current.environment.defaults}
                  environmentFile: ${args.envPath}/.env.my_api2.production
                
                # App Configurations
                configuration/: 
                  onOut|: ${checkVariables}
                  
                  # Default Configuration
                  default:
                    inherit|: ${current.application.defaults}
                    launch$: vpc-private-server
                    create:
                      readYaml|: ${configFile$},${launch$}

                  # High Security Configuration
                  highSecurity:
                    inherit|: ${current.application.defaults}
                    create:
                      vpc:
                        securitygroups: [sg-#hash2]             