--- # My Domain AWS Certificate Request File
domainName: www.mydomain.com
domain/: 
  mydomain: # ${current.domain.name} refers to here
    wildCard: true # Puts "*." infront of the domain name
    extensions:
      - com
      - net
    subDomains:
      - dev
      - staging
      - testing
    

