--- # Cirplus Domain AWS Certificate Request File
domainName: www.cirplus.io
domain/: 
  cirplus: # ${current.domain.name} refers to here
    wildCard: true # Puts "*." infront of the domain name
    extensions:
      - io
      - com
      - de
      - net
    subDomains:
      - africa
      - americas
      - asia
      - company
      - dev
      - europe
      - industry
      - market
      - material
      - search
      - staging
      - testing
      - world
    

