--- # CI-AUTO-DEPLOY Configuration File
config:
  configPath: ${args.configPath}
  readYaml|: ${configPath}/.cipaths.yaml,config,{configPath:\ ${configPath}}

defaults:
  debug: true
  simulate: true

