kwArgs:
  cloudProvider: aws
  cloudService: ebt
  cloudTool: eb
  application: myApi2
  environment: staging
  configFile: .cideploy.yaml
  forceCreate: true
  versionLabel: describe
  descriptionText: null
  versionPrefix: v
  packageFile: package.json
  existingVersion: null
  deployStaged: null
  forceUpdate: null
  revisionPrefix: r
  revisionNumber: auto
  versionSuffix: null
  lastRunFile: .deploy/.last_run.yaml
  region: eu-central-1
  simulate: true
  debug: true
  appConfig: default
  envSuffix: active
  cname: null
  launch: null
  launchFile: .deploy/aws_launch.yaml
