kwArgs:
  cloudProvider: aws
  cloudService: ebt
  cloudTool: eb
  application: all
  environment: staging
  configFile: .cideploy.yaml
  configPath: .ciautodeploy
  forceCreate: true
  versionLabel: describe
  descriptionText: null
  versionPrefix: v
  packageFile: package.json
  existingVersion: null
  deployStaged: null
  forceUpdate: null
  revisionPrefix: r
  revisionNumber: auto
  versionSuffix: null
  lastRunFile: .cilastrun.yaml
  region: eu-central-1
  simulate: true
  debug: true
  appConfig: default
  envSuffix: active
  cname: null
  launch: null
  launchFile: .deploy/aws_launch.yaml
  environmentVariable: CI_AUTO_DEPLOY
  deployPath: .ciautodeploy
  envPath: .envs
  awsLaunchFile: .ciautodeploy/aws_launch.yaml
  awsConfigFile: .ciautodeploy/aws_config.yaml
  secretsPath: .cisecrets
  passwdFile: .cisecrets/.passwd.yaml
  devToken: .cisecrets/.dev_tokens.yaml
  stgToken: .cisecrets/.stg_tokens.yaml
  prodToken: .cisecrets/.prod_tokens.yaml
  cloud-provider: aws
