--- # Configure Paths and Files

config:
  path: ${configPath}
  envPath: ${args.envPath}
  
  cloud/:
    aws:
      path : ${configPath}/.cloud/.aws
      defaultsFile : ${path}/aws_defaults.yaml
      readYaml|: ${defaultsFile},defaults,{path:\ ${path}}
   
  lastRunFile: ${args.lastRunFile}
  secretsPath: ${args.secretsPath}
  passwordFile: ${secretsPath}/${args.passwordFile}
  tokenFiles: 
    testing: ${args.secretsPath}/${args.tokenFiles.testing}
    staging: ${args.secretsPath}/${args.tokenFiles.staging}
    production: ${args.secretsPath}/${args.tokenFiles.production}